# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 320)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Rectangle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Rectangle.setGeometry(QtCore.QRect(20, 80, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_Rectangle.setFont(font)
        self.pushButton_Rectangle.setObjectName("pushButton_Rectangle")
        self.pushButton_Tshape = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Tshape.setGeometry(QtCore.QRect(20, 140, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_Tshape.setFont(font)
        self.pushButton_Tshape.setObjectName("pushButton_Tshape")
        self.pushButton_Specification = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Specification.setGeometry(QtCore.QRect(20, 200, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_Specification.setFont(font)
        self.pushButton_Specification.setObjectName("pushButton_Specification")
        self.comboBox_Security = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Security.setGeometry(QtCore.QRect(180, 20, 160, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBox_Security.setFont(font)
        self.comboBox_Security.setObjectName("comboBox_Security")
        self.comboBox_Security.addItem("")
        self.comboBox_Security.addItem("")
        self.comboBox_Security.addItem("")
        self.textEdit_Security = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Security.setGeometry(QtCore.QRect(180, 80, 160, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_Security.setFont(font)
        self.textEdit_Security.setObjectName("textEdit_Security")
        self.comboBox_Rebar = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Rebar.setGeometry(QtCore.QRect(380, 20, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBox_Rebar.setFont(font)
        self.comboBox_Rebar.setObjectName("comboBox_Rebar")
        self.comboBox_Rebar.addItem("")
        self.comboBox_Rebar.addItem("")
        self.comboBox_Rebar.addItem("")
        self.comboBox_Rebar.addItem("")
        self.comboBox_Rebar.addItem("")
        self.comboBox_Rebar.addItem("")
        self.comboBox_Concrete = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Concrete.setGeometry(QtCore.QRect(530, 20, 70, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBox_Concrete.setFont(font)
        self.comboBox_Concrete.setObjectName("comboBox_Concrete")
        self.comboBox_Concrete.addItem("")
        self.comboBox_Concrete.addItem("")
        self.comboBox_Concrete.addItem("")
        self.comboBox_Concrete.addItem("")
        self.comboBox_Concrete.addItem("")
        self.comboBox_Concrete.addItem("")
        self.comboBox_Concrete.addItem("")
        self.comboBox_Concrete.addItem("")
        self.comboBox_Concrete.addItem("")
        self.comboBox_Concrete.addItem("")
        self.comboBox_Concrete.addItem("")
        self.comboBox_Concrete.addItem("")
        self.comboBox_Concrete.addItem("")
        self.textEdit_Parameters = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Parameters.setGeometry(QtCore.QRect(380, 80, 220, 200))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textEdit_Parameters.setFont(font)
        self.textEdit_Parameters.setObjectName("textEdit_Parameters")
        self.pushButton_Parameters = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Parameters.setGeometry(QtCore.QRect(630, 80, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_Parameters.setFont(font)
        self.pushButton_Parameters.setObjectName("pushButton_Parameters")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Rectangle.setText(_translate("MainWindow", "矩形截面"))
        self.pushButton_Tshape.setText(_translate("MainWindow", "T形截面"))
        self.pushButton_Specification.setText(_translate("MainWindow", "查看规范"))
        self.comboBox_Security.setItemText(0, _translate("MainWindow", "安全等级一级"))
        self.comboBox_Security.setItemText(1, _translate("MainWindow", "安全等级二级"))
        self.comboBox_Security.setItemText(2, _translate("MainWindow", "安全等级三级"))
        self.comboBox_Rebar.setItemText(0, _translate("MainWindow", "HPB300"))
        self.comboBox_Rebar.setItemText(1, _translate("MainWindow", "HRB400"))
        self.comboBox_Rebar.setItemText(2, _translate("MainWindow", "HRBF400"))
        self.comboBox_Rebar.setItemText(3, _translate("MainWindow", "RRB400"))
        self.comboBox_Rebar.setItemText(4, _translate("MainWindow", "HRB500"))
        self.comboBox_Rebar.setItemText(5, _translate("MainWindow", "HRBF500"))
        self.comboBox_Concrete.setItemText(0, _translate("MainWindow", "C20"))
        self.comboBox_Concrete.setItemText(1, _translate("MainWindow", "C25"))
        self.comboBox_Concrete.setItemText(2, _translate("MainWindow", "C30"))
        self.comboBox_Concrete.setItemText(3, _translate("MainWindow", "C35"))
        self.comboBox_Concrete.setItemText(4, _translate("MainWindow", "C40"))
        self.comboBox_Concrete.setItemText(5, _translate("MainWindow", "C45"))
        self.comboBox_Concrete.setItemText(6, _translate("MainWindow", "C50"))
        self.comboBox_Concrete.setItemText(7, _translate("MainWindow", "C55"))
        self.comboBox_Concrete.setItemText(8, _translate("MainWindow", "C60"))
        self.comboBox_Concrete.setItemText(9, _translate("MainWindow", "C65"))
        self.comboBox_Concrete.setItemText(10, _translate("MainWindow", "C70"))
        self.comboBox_Concrete.setItemText(11, _translate("MainWindow", "C75"))
        self.comboBox_Concrete.setItemText(12, _translate("MainWindow", "C80"))
        self.pushButton_Parameters.setText(_translate("MainWindow", "确定参数"))

